### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by SahilFruitwala** [Kikobeats/awesome-api#30]
In the free section of the Documentation part, there are **demo** links beside the **GitHub repository** link. Any of these demo links are not working.

**Comment by Kikobeats** [comment]
Can you make a PR removing the links? 🙂

**Comment by SahilFruitwala** [comment]
Sorry this is first time on open source, can you tell me what's PR means?

**Comment by SahilFruitwala** [comment]
Sure. I will do that.
